/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.ueats;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;

import dao.BillDao;
import dao.CategoryDao;
import dao.ProductDao;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;
import model.Product;

/**
 *
 * @author LENOVO
 */
public class PlaceOrder extends javax.swing.JFrame {
    public int billId=1;
    public int grandTotal=0;
    public int productPrice=0;
    public int productTotal=0;
    public String emailPattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String phonenoPattern="^[0-9]*$";
    public String userEmail;

    /** Creates new form PlaceOrder */
    public PlaceOrder() {
        initComponents();
    }
    
    public PlaceOrder(String email) {
        initComponents();
        txtprodname.setEditable(false);
        txtprodprice.setEditable(false);
        txtprodtotal.setEditable(false);
        btnaddtocart.setEnabled(false);
        btngeneratebill.setEnabled(false);
        JFormattedTextField tf=((JSpinner.DefaultEditor)jSpinner1.getEditor()).getTextField();
        tf.setEnabled(false);
        userEmail=email;
    }
    
    public void productNameByCategory(String category){
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list =ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr=list.iterator();
        while(itr.hasNext()){
            Product productObj =itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
            
        }
    }
    
        public void filterProductByname(String name,String category){
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list =ProductDao.filterProductByName(name,category);
        Iterator<Product> itr=list.iterator();
        while(itr.hasNext()){
            Product productObj =itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
            
        }
        
    }
        
        public void clearProductFields(){
         txtprodname.setText("");
        txtprodprice.setText("");
        jSpinner1.setValue(1);
        txtprodtotal.setText("");
        btnaddtocart.setEnabled(false);
       
        }
        
        public void validateField(){
            String customerName=txtcustname.getText();
            String customerPhonenumber=txtcustphoneno.getText();
            String customerEmail=txtcustemail.getText();
            if(!customerEmail.equals("")&&customerPhonenumber.matches(phonenoPattern)&&customerPhonenumber.length()==10&&customerEmail.matches(emailPattern)&& grandTotal >0 ){
                btngeneratebill.setEnabled(true);
            }
            else{
                btngeneratebill.setEnabled(false);
            }
        }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcustphoneno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcustemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtprodname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprodprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        txtprodtotal = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnaddtocart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        lblgrandtotal = new javax.swing.JLabel();
        btngeneratebill = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 28));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 82, 70, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer Details:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 157, -1, -1));

        txtcustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustnameActionPerformed(evt);
            }
        });
        txtcustname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustnameKeyReleased(evt);
            }
        });
        getContentPane().add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 192, 200, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 232, 110, -1));

        txtcustphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustphonenoActionPerformed(evt);
            }
        });
        txtcustphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustphonenoKeyReleased(evt);
            }
        });
        getContentPane().add(txtcustphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 261, 200, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 307, 46, -1));

        txtcustemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustemailActionPerformed(evt);
            }
        });
        txtcustemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustemailKeyReleased(evt);
            }
        });
        getContentPane().add(txtcustemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 343, 200, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Category");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 82, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 117, 200, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 157, 47, -1));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 192, 200, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 261, 200, 375));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 82, 43, -1));

        txtprodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtprodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 117, 202, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 82, 43, -1));

        txtprodprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprodprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 117, 201, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantity:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 157, 67, -1));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 192, 202, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 157, 52, -1));

        txtprodtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodtotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtprodtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 192, 201, -1));

        btnclear.setBackground(new java.awt.Color(51, 153, 255));
        btnclear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 241, -1, -1));

        btnaddtocart.setBackground(new java.awt.Color(0, 153, 255));
        btnaddtocart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnaddtocart.setText("Add to Cart");
        btnaddtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtocartActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 241, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 283, 471, 353));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Grand Total: Rs.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 675, -1, -1));

        lblgrandtotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblgrandtotal.setForeground(new java.awt.Color(255, 255, 255));
        lblgrandtotal.setText("000");
        getContentPane().add(lblgrandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 675, 43, -1));

        btngeneratebill.setBackground(new java.awt.Color(51, 153, 255));
        btngeneratebill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btngeneratebill.setText("Generate Bill & Print");
        btngeneratebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratebillActionPerformed(evt);
            }
        });
        getContentPane().add(btngeneratebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 672, -1, -1));

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 51, 51));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1263, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustnameActionPerformed

    private void txtcustphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustphonenoActionPerformed

    private void txtcustemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustemailActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtprodtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodtotalActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home(userEmail).setVisible(true);
    }//GEN-LAST:event_btncloseActionPerformed

    private void txtprodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodnameActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        clearProductFields();
    }//GEN-LAST:event_btnclearActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId=Integer.parseInt(BillDao.getId());
        jLabel3.setText(BillDao.getId());
        ArrayList<Category> list=CategoryDao.getAllRecords();
        Iterator<Category> itr=list.iterator();
        while(itr.hasNext()){
            Category categoryObj =itr.next();
            jComboBox1.addItem(categoryObj.getName());
        
        }
        String category =(String) jComboBox1.getSelectedItem();
        productNameByCategory(category);
    }//GEN-LAST:event_formComponentShown

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        String name =txtsearch.getText();
        String category =(String)jComboBox1.getSelectedItem();
        filterProductByname(name,category);
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        String productName=(String) model.getValueAt(index, 0);
        Product product =ProductDao.getProductByname(productName);
        txtprodname.setText(product.getName());
        txtprodprice.setText(product.getPrice());
        jSpinner1.setValue(1);
        txtprodtotal.setText(product.getPrice());
        productPrice=Integer.parseInt(product.getPrice());
        productTotal=Integer.parseInt(product.getPrice());
        btnaddtocart.setEnabled(true);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int quantity=(Integer) jSpinner1.getValue();
        if(quantity<=1){
            jSpinner1.setValue(1);
            quantity=1;
        }
        productTotal =productTotal*quantity;
        txtprodtotal.setText(String.valueOf(productTotal));
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String category =(String)jComboBox1.getSelectedItem();
        productNameByCategory(category);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnaddtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtocartActionPerformed
        // TODO add your handling code here:
        String name=txtprodname.getText();
        String price =txtprodprice.getText();
        String quantity=String.valueOf(jSpinner1.getValue());
        DefaultTableModel dtm=(DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name,price,quantity,productTotal});
        grandTotal=grandTotal+productTotal;
        lblgrandtotal.setText(String.valueOf(grandTotal));
        
        clearProductFields();
        validateField();
        
        
        
    }//GEN-LAST:event_btnaddtocartActionPerformed

    private void txtcustnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustnameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtcustnameKeyReleased

    private void txtcustphonenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustphonenoKeyReleased
        // TODO add your handling code here:
         validateField();
    }//GEN-LAST:event_txtcustphonenoKeyReleased

    private void txtcustemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustemailKeyReleased
        // TODO add your handling code here:
         validateField();
    }//GEN-LAST:event_txtcustemailKeyReleased

    private void btngeneratebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratebillActionPerformed
        // TODO add your handling code here:
        String customerName=txtcustname.getText();
        String customerPhonenumber=txtcustphoneno.getText();
        String customerEmail=txtcustemail.getText();
        SimpleDateFormat dFormat =new SimpleDateFormat("dd-mm-yyyy");
        Date date=new Date();
        String todaydate=dFormat.format(date);
        String total=String.valueOf(grandTotal);
        String createdBy=userEmail;
        Bill bill=new Bill();
        bill.setId=(billId);
        bill.setName(customerName);
        bill.setPhoneNumber(customerPhonenumber);
        bill.setEmail(customerEmail);
        bill.setDate(todaydate);
        bill.setTotal(total);
        bill.setCreatedBy(createdBy);
        BillDao.save(bill);
        
        // creating document;
        
        String path="D:\\";
        com.itextpdf.text.Document doc =new com.itextpdf.text.Document();
        
        try{
            PdfWriter.getInstance(doc,new FileOutputStream(path+""+billId+".pdf"));
            doc.open();
            Paragraph ResturantName =new Paragraph("                                                                                                                Uber*Eats*Resto*\n");
            doc.add(ResturantName);
            Paragraph startLine =new Paragraph("************************************************************************************************************************************\n");
            doc.add(startLine);
            Paragraph paragaraph3=new Paragraph("\t Bill Id:"+billId+"\nCustomer Name: "+customerName+"Total Paid:"+grandTotal+"");
            doc.add(paragaraph3);
            doc.add(startLine);
          PdfPTable tbl =new PdfPTable (4);

        
            tbl.addCell("Name");
            tbl.addCell("Price");
            tbl.addCell("Quantity");
            tbl.addCell("Total");
            
            for(int i=0;i<jTable2.getRowCount();i++){
                String n=jTable2.getValueAt(i, 0).toString();
                String d=jTable2.getValueAt(i, 1).toString();
                String r=jTable2.getValueAt(i, 2).toString();
                String q=jTable2.getValueAt(i, 3).toString();
                tbl.addCell(n);
                tbl.addCell(d);
                tbl.addCell(r);
                tbl.addCell(q);
            }
            doc.add(tbl);
            doc.add(startLine);
            Paragraph thanksMsg=new Paragraph("Thankyou,Please Visit Again.");
            doc.add(thanksMsg);
            OpenPdf.openById(String.valueOf(billId));
            
            
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null,e);
            
        }
        doc.close();
        setVisible(false);
        new PlaceOrder(createdBy).setVisible(true);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btngeneratebillActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
         int index=jTable2.getSelectedRow();
         int a=JOptionPane.showConfirmDialog(null, "Do You Want To Remove This Product","Select",JOptionPane.YES_NO_OPTION);
         if(a==0)
         {
             TableModel model=jTable2.getModel();
             String total=model.getValueAt(index, 3).toString();
             grandTotal=grandTotal -Integer.parseInt(total);
             lblgrandtotal.setText(String.valueOf(grandTotal));
             ((DefaultTableModel)jTable2.getModel()).removeRow(index);
             
         }
       
    
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtprodpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodpriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddtocart;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btngeneratebill;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblgrandtotal;
    private javax.swing.JTextField txtcustemail;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtcustphoneno;
    private javax.swing.JTextField txtprodname;
    private javax.swing.JTextField txtprodprice;
    private javax.swing.JTextField txtprodtotal;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

}
